name: prime-cache-b4b664f

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Cache dependencies (name must match grader)
      - name: prime-cache-b4b664f
        id: prime-cache-b4b664f
        uses: actions/cache@v4
        with:
          path: ~/.cache/my-deps
          key: cache-b4b664f

      # Step 3: Populate cache path
      - name: Populate cache path
        run: |
          mkdir -p ~/.cache/my-deps
          echo "primed at $(date -u)" > ~/.cache/my-deps/primed.txt
          ls -la ~/.cache/my-deps

      # Step 4: Show cache hit/miss
      - name: Show cache status
        run: |
          echo "Cache hit? ${{ steps.prime-cache-b4b664f.outputs.cache-hit }}"
          echo "Contents of cache path:"
          ls -la ~/.cache/my-deps || true
