name: Email Step Test

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f2007761@ds.study.iitm.ac.in
        run: echo "Hello, world!"
