name: Email Step Workflow

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f2007761@ds.study.iitm.ac.in
        run: echo "Step with email address executed successfully"
