name: Email Step Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 24f2007761@ds.study.iitm.ac.in
        run: echo "Hello, world! This step is tagged with my email."
