name: Test Email Step

on:
  workflow_dispatch:  # manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 24f2007761@ds.study.iitm.ac.in
        run: echo "Hello, grader! This step contains my email."
