name: Log ISS Location Data Daily

on:
  schedule:
    - cron: "0 12 * * *"  # Runs at 12:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  collect-iss-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 24f2007761@ds.study.iitm.ac.in
        run: echo "This step has my email in the name!"

      - name: Fetch ISS location data
        run: |
          python3 - << 'EOF'
          import requests
          data = requests.get('http://api.open-notify.org/iss-now.json').text
          with open('iss-location.jsonl', 'a') as f:
              f.write(data + '\n')
          EOF

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add iss-location.jsonl
          git commit -m "Update ISS position data [skip ci]" || exit 0
          git push
