name: Email Check

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 24f2007761@ds.study.iitm.ac.in   # 👈 required email in step name
        run: echo "Hello, world!"
