name: Email Check

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f2007761@ds.study.iitm.ac.in   # must match exactly
        run: echo "Hello, world!"
