name: Cache Dependencies

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-with-cache:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/dependencies
          key: cache-b4b664f
          restore-keys: cache-b4b664f
      
      - name: prime-cache-b4b664f
        run: |
          echo "Cache hit result: ${{ steps.cache-deps.outputs.cache-hit }}"
      
      - name: Create cache content
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.cache/dependencies
          echo "cached" > ~/.cache/dependencies/data.txt
