name: Cache Example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/my-deps
          key: cache-b4b664f

      - name: prime-cache-b4b664f
        run: echo "Cache result: ${{ steps.cache.outputs.cache-hit }}"
